name: Build, push and deploy dynamic-dns

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Login to container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ steps.login-ecr.outputs.registry }}
          username: AWS
          password: ${{ steps.login-ecr.outputs.docker_password }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          file: Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.login-ecr.outputs.registry }}/django-dynamic-dns:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-k8s:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Set up kubeconfig
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy
        run: kubectl rollout restart deployment/dynamic-dns -n default

      - name: Wait for pod to start
        run: |
          echo "Waiting for dynamic-dns deployment to complete..."
          kubectl rollout status deployment/dynamic-dns -n default --timeout=600s
